const routes = {
    home: '/',
    search: '/search',
    product: '/product',
    profile: '/profile/:userId',
    productDetail: '/product/:productId',
    updateProduct: '/updateProduct/:productId',
    addProduct: '/addProduct',
    cart: '/cart',
    cartsId: '/carts/:id',
    checkout: '/checkout',
    admin: '/admin',
    login: '/login',
    order: '/orders',
    address: '/address',
    category: '/category/:categoryId',
    register: '/register',
    news : '/news',
    addNew : '/addNew',
    updateNew : '/updateNew/:bannerId',
    sales : '/sales',
    updateSale: '/updateSale/:saleId',
    addSale: '/addSale',
    forgotpassword: '/forgot-password',
    checkout: '/checkout',
};

export default routes;
